server:
  port: 8761

spring:
  application:
    name: sct-eureka

eureka:
  instance:
    hostname: sct-eureka #Windows系统配置host C:\Windows\System32\drivers\etc hosts文件。设置 127.0.0.1 sct-eureka,则sct-eureka代表127.0.0.1
#    prefer-ip-address: true #的作用是注册服务的时候使用ip地址，ip地址从host里面找
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://sct-eureka8002:8002/eureka/
      defaultZone: http://localhost:${server.port}/eureka/

