server:
  port: 6061
spring:
  application:
    name: dc-server
  redis:
    database: 5
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

jwt:
  token-header: Authorization
  expire: 14400
  secret: MTIzNDU2