spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: tiger
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
#    url: jdbc:oracle:thin:@192.168.43.9:1521:ORCL
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0