spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/myschool?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  redis:
    database: 0
    host: 127.0.0.1
#    host: 192.168.43.132
    port: 6379
    timeout: 10
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMaxWait: 500
 #   password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: 100
        max-idle: 800
        min-idle: 500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

file:
  upload: D:/fileUpload/

feign:
  hystrix:
    enabled: true